### ISSUE TITLE
Option to preserve past events that have been removed from source

### ISSUE THREAD

**Issue by non-bin** [derekantrican/GAS-ICS-Sync#117]
A calendar I sync from removes events after they have passed, an option (per source calendar?) to cause `processEventCleanup()` to ignore past events would be beneficial.

I still want events in the future to be removed if they are cancelled, so `removeEventsFromCalendar = false` would not work

**Comment by jonas0b1011001** [comment]
Are you looking for the same thing as #109 ?

**Comment by non-bin** [comment]
Yes, thank you. Is this likely to be added as a feature? I would be happy to create a pull request with the changes

**Comment by derekantrican** [comment]
At this point I don't think we'll include it as a standard feature as it's a non-standard situation (ICS source calendar removing events as they've passed, but you want to keep them on your calendar - usually ICS calendars *don't* do that). But so far we've had 2 people with this situation so if we get a lot of people requesting this it would definitely be a good reason to have a built-in feature.

Since your issue is solved, I'm going to go ahead and close this issue.

**Comment by hubikj** [comment]
@derekantrican Sorry for replying to an old closed issue. Unfortunately, this is a standard behavior. I have Outlook 365 calendar at work and it has exactly this behavior - the ICS contains only recent events. Anything older than 1 month is removed, which is really annoying. It would be best to have sync option to not remove anything older than 1 month.

**Comment by derekantrican** [comment]
@hubikj per https://github.com/derekantrican/GAS-ICS-Sync/issues/125 the published time range of Outlook events is 3 months ago to 6 months from now. If you are an admin of your Office 365 account you can change it by following these steps: https://github.com/derekantrican/GAS-ICS-Sync/issues/125#issuecomment-631626145

As far as a change to the script, have you looked at https://github.com/derekantrican/GAS-ICS-Sync/issues/168#issuecomment-734653434?

**Comment by hubikj** [comment]
@derekantrican I am not the admin of our corporate email, so I cannot change this. I used the modification from #168 successfully, but I think it should be a standard part of this script since it is super helpful. I just commented here to say that this behavior is more common than you may think. Thanks a lot!

**Comment by lyssbjack** [comment]
Just popping in to one up this functionality.  I have multiple cals I'm subscribed to that do not keep past events.
