### ISSUE TITLE
Error message when trying to uninstall

### ISSUE THREAD

**Issue by tdechter** [derekantrican/GAS-ICS-Sync#134]
When trying to uninstall the older version of the script I get this message:
 

![GAS error message](https://user-images.githubusercontent.com/66752712/84319030-58d61000-ab3d-11ea-8291-6820987646f9.PNG)

**Comment by tdechter** [comment]
I get the same error message with that function too.

**Comment by jonas0b1011001** [comment]
I'm not 100% sure what you are trying to accomplish.
The error message is usually caused by a wrongly formatted _sourceCalendars_ variable in the settings section.

Uninstalling the script is nothing else then deleting the trigger that makes it run in the defined interval. You can visit [https://script.google.com/home/triggers](https://script.google.com/home/triggers) to see all triggers that are currently set up in your account. If you want to uninstall the script, just remove its triggers from the list and delete the script file from your Google Drive.

**Comment by tdechter** [comment]
Thanks.  I removed any of the triggers for the old script this way and
deleted the script from my drive.
