### ISSUE TITLE
Be able to filter out events with specific text in event title

### ISSUE THREAD

**Issue by alexjames623** [derekantrican/GAS-ICS-Sync#138]
Basically, I'm importing events from an ICS calendar file. Within the ICS calendar file, the user's "unavailability" time is actually in the form of ICS events themselves. This app adds these "unavailable" times to the google calendar as events, when I'd rather them not be added to the google calendar at all.

For example, here is a typical schedule (these are all ICS events):
"Unavailable" 5pm-8am
"Event 1" 8am-12pm
"Unavailable" (Lunch break) 12pm-1pm
"Event 2" 1pm-5pm
"Unavailable" 5pm-8am

It would be nice if there is a feature to simply ignore any events that include text "Unavailable" so these events are completely omitted from the google calendar.

**Comment by jonas0b1011001** [comment]
#69 would also cover your use case, no work has been done on that one though.

However you can quite easily make it skip the Unavailable events by changing [line 227](https://github.com/derekantrican/GAS-ICS-Sync/blob/763f219a9e0162befcd332eb930271bcf0b81132/Helpers.gs#L227) to
`if ((onlyFutureEvents && checkSkipEvent(event, icalEvent)) || (icalEvent.summary.includes('Unavailable'))){`

**Comment by alexjames623** [comment]
Awesome! That seemed to do the trick.

Thank you

**Comment by kdwhitmire** [comment]
> #69 would also cover your use case, no work has been done on that one though.
> 
> However you can quite easily make it skip the Unavailable events by changing [line 227](https://github.com/derekantrican/GAS-ICS-Sync/blob/763f219a9e0162befcd332eb930271bcf0b81132/Helpers.gs#L227) to `if ((onlyFutureEvents && checkSkipEvent(event, icalEvent)) || (icalEvent.summary.includes('Unavailable'))){`

@jonas0b1011001 , could you suggest a further enhancement for this line where I filter a certain text only for a certain calendar?  For example, I have a weird situation where URL.ics contains events that I really want to be on two different calendars in Google.  So really I want the "filter" logic to be WHERE event in URL.ics contains "XYZ" post those to Google Calendar "A".  And then a separate line for WHERE event in URL.ics contains "ABC" post those to Google Calendar "B".  But it would also need to ignore all other URLxx.ics that I'm running through the script because I've got about 8 different calendars that I sync here.
