### ISSUE TITLE
More flexibility in scheduling a trigger

### ISSUE THREAD

**Issue by derekantrican** [derekantrican/GAS-ICS-Sync#255]
Currently, we use the `everyMinutes` function to schedule triggers, but according to [the docs](https://developers.google.com/apps-script/reference/script/clock-trigger-builder#everyminutesn) this only accepts 1, 5, 10, 15 or 30 as an input. We should allow a bit of greater flexibility that if you put in 60, 120, or some other multiple of 60 for `howFrequent` then we should use the `everyHours` function instead

**Comment by Lonestarjeepin** [comment]
So I played around with this (with some help from chatGPT because the last time I wrote Javascript was 20 years ago...) and came up with this code.  It works, but for some reason when I run Install, the log shows the "Intended Frequency/Adjusted Frequency" verbiage twice... so there's a bug somewhere I'm missing.  I also don't know how to submit a pull request in Github so this is the best version I have of sharing code back to you!

//Same howFrequent variable, but I added more comments to explain acceptable inputs and how those will be manipulated.
var howFrequent = 5;                     // What interval (minutes) to run this script on to check for new events.  Any integer can be used, but will be rounded up to 5, 10, 15, 30 or to the nearest hour after that.. 60, 120, etc. 1440 (24 hours) is the maximum value.  Anything above that will be replaced with 1440.


//***************Modified Install function in Code.gs:*******************
function install() {
  // Delete any already existing triggers so we don't create excessive triggers
  deleteAllTriggers();

  // Schedule sync routine to explicitly repeat and schedule the initial sync
  var adjustedMinutes = getValidTriggerFrequency(totalMinutes);
  if (adjustedMinutes >= 60) {
    ScriptApp.newTrigger("startSync")
      .timeBased()
      .everyHours(adjustedMinutes / 60)
      .create();
  } else {
    ScriptApp.newTrigger("startSync")
      .timeBased()
      .everyMinutes(adjustedMinutes)
      .create();
  }
  ScriptApp.newTrigger("startSync").timeBased().after(1000).create();

  // Schedule sync routine to look for update once per day using everyDays
  ScriptApp.newTrigger("checkForUpdate")
    .timeBased()
    .everyDays(1)
    .create();
}

***************Modified getValidTriggerFrequency function in Helpers.gs****************

function getValidTriggerFrequency(origFrequency) {
  if (!origFrequency > 0) {
    Logger.log("No valid frequency specified. Defaulting to 15 minutes.");
    return 15;
  }

  // Limit the original frequency to 1440
  origFrequency = Math.min(origFrequency, 1440);

  var acceptableValues = [5, 10, 15, 30].concat(
    Array.from({ length: 24 }, (_, i) => (i + 1) * 60)
  ); // [5, 10, 15, 30, 60, 120, ..., 1380, 1440]

  // Find the smallest acceptable value greater than or equal to the original frequency
  var roundedUpValue = acceptableValues.find(value => value >= origFrequency);

  Logger.log(
    "Intended frequency = " + origFrequency + ", Adjusted frequency = " + roundedUpValue
  );
  return roundedUpValue;
}

String.prototype.includes = function(phrase){
  return this.indexOf(phrase) > -1;
}
