### ISSUE TITLE
[Request] Only sync Future Events but also delete them

### ISSUE THREAD

**Issue by mhardy** [derekantrican/GAS-ICS-Sync#378]
### Describe the solution you'd like

var onlyFutureEvents = true;
// If you turn this to "true", past events will not be synced (this will also removed past events from the target calendar if removeEventsFromCalendar is true)

It would be nice to have onlyFutreEvents true to make the sync faster, but also leave removeEventFromCalendar also true so any future events that are deleted get removed, but past events aren't touched.

**Comment by jonas0b1011001** [comment]
This should be covered by #317, you can follow [https://github.com/derekantrican/GAS-ICS-Sync/wiki/Setting-up-the-script-manually](https://github.com/derekantrican/GAS-ICS-Sync/wiki/Setting-up-the-script-manually) to update.

**Comment by Ayal1** [comment]
> This should be covered by #317, you can follow https://github.com/derekantrican/GAS-ICS-Sync/wiki/Setting-up-the-script-manually to update.

I'm not sure this is covered, and if so how would this be achieved? Because in my script I have `onlyFutureEvents = true` and `removeEventsFromCalendar = false` since I don't want the script to remove past events that were subsequently removed from the source calendar (unless I manually remove them from the script-created calendar), but I do want it to remove future events that were removed from the source calendar (since they were cancelled). 

At the moment, with these settings applied, I could have a future event added to the source calendar but if it is completely removed instead of modified to a new date, the event remains and I have to go manually check the source calendar to make sure it is indeed happening.

**Comment by jonas0b1011001** [comment]
After updating you have a new setting, have you tried:
```
var onlyFutureEvents = true; 
var removeEventsFromCalendar = true;
var removePastEventsFromCalendar = false;
```
?

**Comment by Ayal1** [comment]
Ah, that's my issue. I just assumed since this was closed in March that it was already in the releases but now I see that the latest one is from January. I'll copy over the files manually now, thanks!
