### ISSUE TITLE
Script function not found: doGet

### ISSUE THREAD

**Issue by DannyLeiton** [derekantrican/GAS-ICS-Sync#54]
Script function not found: doGet

I've got this Error when I publish and open the script. 
I noticed about it when I was finding why the Calendar does not update after installing this script.
Thanks for your help.

**Comment by derekantrican** [comment]
Please share your script with me: derekantrican@gmail.com

**Comment by DannyLeiton** [comment]
I see what is happening, your script works for "My Calendars", and it does not recognize "Other Calendars".

**Comment by DannyLeiton** [comment]
I shared my script with you @derekantrican, I already have a Google Calendar (with a nice tinyurl created and QR printed) of kind "Other Calendars", this calendar brings the info from my airbnb ical calendar. Since it takes way looong to update, I found your script and made it work, buuut it gets the Calendar by Name from the kind of "My Calendars", if it does not exist in the "My Calendars" Array, then it creates it and syncs it with my ical calendar. 
That's the issue, I need the script to recognize my already existing "Other Calendars" Calendar and update it. Ooor, I'll need to find a way to redirect this already existing "Other Calendar" Calendar, to a new Calendar of kind "My Calendars", generated by this script, because I'd NOT like to change my already existing super cool tinyurl. Let me know if I explained myself clearly. 
Kind Regards.

**Comment by jonas0b1011001** [comment]
You want the script to add events to a calendar that you subscribed to via a url?
That's not possible as subscribed calendars are read only, no was to change that.

**Comment by derekantrican** [comment]
@DannyLeiton Similar to what @jonas0b1011001 said, the "Other Calendars" section is read-only. Because we are circumventing Google's "subscribe to calendar" feature, we can only create events where you could also create events manually. You can see which calendars the script can work on by creating an event, then selecting a calendar to put it on:

![image](https://user-images.githubusercontent.com/1558019/65251084-8d83d200-daab-11e9-8bb0-d4caebf662d5.png)

Alternatively, it sounds like you could create something similar to what you have going on by either using 2 different instances of my program to sync your desired calendar in "Other calendars" and your Airbnb ical to the same calendar in "My calendars". Let me know if you want me to help you set this up.
