### ISSUE TITLE
Execution failed: Event start date must be before event end date.

### ISSUE THREAD

**Issue by Zangoran** [derekantrican/GAS-ICS-Sync#57]
Link to my ICS feed (from Canvas, it is a school tool for tracking assignments and stuff):
https://uwplt.instructure.com/feeds/calendars/user_ltI6MNY6ML1ZsYNEL9zwrRBiV38kZcB97NTZagce.ics

This is the error: Execution failed: Event start date must be before event end date. (line 172, file "Code")

I looked through the past issues that looked like this, but couldn't really figure it out. I have the default duration as 60 minutes, not really sure why this doesn't just override the time error.

**Comment by jonas0b1011001** [comment]
Please try [this](https://github.com/derekantrican/GAS-ICS-Sync/issues/56#issuecomment-537569326)!

**Comment by Zangoran** [comment]
@jonas0b1011001 That worked! Thanks!
Is there a reason that isn't merged into the current version yet?

**Comment by derekantrican** [comment]
@jonas0b1011001 *Technically speaking* this format of ics doesn't conform to the [standard](https://tools.ietf.org/html/rfc5545). But we've seen a lot of people have this problem recently so we'll implement the fix for everyone soon.

**Comment by jonas0b1011001** [comment]
In case you want to report the issues to whoever is responsible for creating these ics files (and for the sake of completeness):
in contrast to the example used in [this comment](https://github.com/derekantrican/GAS-ICS-Sync/issues/55#issuecomment-534003159) your events do have the Value=Date property but the date itself is specified in Date-Time format. This (in addition to point 2 in the mentioned comment) is invalid because according to RFC 5545 the

> Value MUST match value type

**Comment by Zangoran** [comment]
Very interesting, yeah I dont think contacting the people with that ics will work.
