### ISSUE TITLE
Constant failed executions from previously stable operation

### ISSUE THREAD

**Issue by yellowbarchetta** [derekantrican/GAS-ICS-Sync#96]
- Description of the problem
I'm getting the following errors each time I run, whether from the console or from a trigger
Jan 30, 2020, 3:42:37 PM	Error	TypeError: Cannot call method "toString" of undefined.
    at processEvent(Helpers:163)
    at [unknown function](Code:175)
    at startSync(Code:174)

- Screenshots
- An input ics string that can reproduce the problem

It was all working fine and dandy up until today.  May not be a bug strictly, but it is annoying.  Log execution shows nothing failing.

**Comment by derekantrican** [comment]
@yellowbarchetta Can you make sure you are using the latest version of the program? If so, can you share that line (and maybe a bit of context)?

**Comment by yellowbarchetta** [comment]
To help me debug some earlier issues with emailing I think I'd added some logging which was failing on the code below in the processEvent function which i'd placed right after:-
 //------------------------ Send event object to gcal ------------------------
    if (needsUpdate){
      if (modifyExistingEvents){

This is the line it was barfing over.  I commented it out and got a successful completion, but haven't captured the specific event that it had issues with.  I'll reinstate the line and post back here if it continues to fail, unless there's something blindingly obvious with my code line below. 

Logger.log("Updating existing event " + newEvent.extendedProperties.private["id"] + newEvent.summary + newEvent.start.dateTime.toString());

**Comment by derekantrican** [comment]
So based on what you just shared it seems that it's having a problem with `newEvent.start.dateTime.toString();`. Fortunately, this is a `Logger.log` method so it's not used.

Note that sometimes `newEvent.start` can be a datetime and sometimes it can be a date (all-day events). I would suggest removing the `.dateTime` portion and doing `newEvent.start.toString()` and see how that works out.

Since this isn't throwing an error when you comment out the log line, it sounds like the actual functionality of the program is working fine. I'm going to close this for now but if it turns out to be a problem later, please come back and comment here.
